version: '3.8'

services:
  php:
    build:
      dockerfile: .docker/Dockerfile
      context: ./
    command:
      - php
      - -S
      - 0.0.0.0:80
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      TZ: Europe/Moscow
      DB_HOST: db
      DB_NAME: test
      DB_USER: test
      DB_PASSWORD: test
    ports:
      - "80:80"
    extra_hosts:
      - host.docker.internal:172.17.0.1
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      TZ: Europe/Moscow
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_RANDOM_ROOT_PASSWORD: 1
