version: '3.8'

services:
  php:
    build:
      dockerfile: .docker/Dockerfile
      context: ./
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      TZ: Europe/Moscow
      DB_HOST: db
      DB_NAME: test
      DB_USER: test
      DB_PASSWORD: test
      XDEBUG_MODE: 'develop,debug,coverage'
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      PHP_IDE_CONFIG: 'serverName=docker'

    extra_hosts:
      - host.docker.internal:172.17.0.1
  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      TZ: Europe/Moscow
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_RANDOM_ROOT_PASSWORD: 1
